name: Docker Image CI
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERSION: $(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Version Check
      run: echo "the version is: $VERSION"    
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag registry.azeemwaqar.com/splitwise-mcp:$VERSION
    - name: Push the Docker Image
      run: docker push registry.azeemwaqar.com/splitwise-mcp:$VERSION
